#!/bin/bash
git submodule add git@github.com:chefspec/chefspec.git apps/chefspec
git submodule add git@github.com:grosser/parallel_tests.git apps/parallel_tests
git submodule add git@github.com:mizzy/serverspec.git apps/serverspec
git submodule add git@github.com:sporkrb/spork.git apps/spork
git submodule add git@github.com:guard/guard-rspec.git apps/guard
git submodule add git@github.com:email-spec/email-spec.git apps/email-spec
git submodule add git@github.com:zipmark/rspec_api_documentation.git apps/rspec_api_documentation
git submodule add git@github.com:brooklynDev/airborne.git apps/airborne
git submodule add git@github.com:yujinakayama/transpec.git apps/transpec
git submodule add git@github.com:paulelliott/fabrication.git apps/fabrication
git submodule add git@github.com:jnicklas/turnip.git apps/turnip
git submodule add git@github.com:collectiveidea/json_spec.git apps/json_spec
git submodule add git@github.com:cucumber/aruba.git apps/aruba
git submodule add git@github.com:cavalle/steak.git apps/steak
git submodule add git@github.com:thekompanee/fuubar.git apps/fuubar
git submodule add git@github.com:jimweirich/rspec-given.git apps/rspec-given
git submodule add git@github.com:k1LoW/awspec.git apps/awspec
git submodule add git@github.com:mattsears/nyan-cat-formatter.git apps/nyan-cat-formatter
git submodule add git@github.com:mongoid/mongoid-rspec.git apps/mongoid-rspec
git submodule add git@github.com:rodjek/rspec-puppet.git apps/rspec-puppet
git submodule add git@github.com:philostler/rspec-sidekiq.git apps/rspec-sidekiq
git submodule add git@github.com:rubocop-rspec/rubocop-rspec.git apps/rubocop-rspec