#!/bin/bash
git submodule add git@github.com:HabitatMap/AirCasting.git apps/AirCasting
git submodule add git@github.com:codefirst/AsakusaSatellite.git apps/AsakusaSatellite
git submodule add git@github.com:askaway/askaway.git apps/askaway
git submodule add git@github.com:Darep/Beatstream.git apps/Beatstream
git submodule add git@github.com:ets-berkeley-edu/calcentral.git apps/calcentral
git submodule add git@github.com:chloerei/campo.git apps/campo
git submodule add git@github.com:assemblymade/coderwall.git apps/coderwall
git submodule add git@github.com:codetriage/codetriage.git apps/codetriage
git submodule add git@github.com:SIGIRE/CoRM.git apps/CoRM
git submodule add git@github.com:covoiturage-libre/covoiturage-libre.git apps/covoiturage-libre
git submodule add git@github.com:riseuplabs/crabgrass-core.git apps/crabgrass-core
git submodule add git@github.com:crowdAI/crowdai.git apps/crowdai
git submodule add git@github.com:Crowdtilt/CrowdtiltOpen.git apps/CrowdtiltOpen
git submodule add git@github.com:JonJagger/cyber-dojo.git apps/cyber-dojo
git submodule add git@github.com:r888888888/danbooru.git apps/danbooru
git submodule add git@github.com:griffithlab/dgi-db.git apps/dgi-db
git submodule add git@github.com:ekylibre/ekylibre.git apps/ekylibre
git submodule add git@github.com:encrypt-to/encrypt.to.git apps/encrypt.to
git submodule add git@github.com:EOL/eol.git apps/eol
git submodule add git@github.com:expertiza/expertiza.git apps/expertiza
git submodule add git@github.com:fairmondo/fairmondo.git apps/fairmondo
git submodule add git@github.com:codeforamerica/follow-all.git apps/follow-all
git submodule add git@github.com:benwbrum/fromthepage.git apps/fromthepage
git submodule add git@github.com:dankleiman/graff_mags.git apps/graff_mags
git submodule add git@github.com:rysmith/hashrobot.git apps/hashrobot
git submodule add git@github.com:scott/helpy.git apps/helpy
git submodule add git@github.com:hitobito/hitobito.git apps/hitobito
git submodule add git@github.com:houston/houston-core.git apps/houston-core
git submodule add git@github.com:inaturalist/inaturalist.git apps/inaturalist
git submodule add git@github.com:intercity/intercity-next.git apps/intercity-next
git submodule add git@github.com:somlor/kanban.git apps/kanban
git submodule add git@github.com:mquan/lavish.git apps/lavish
git submodule add git@github.com:leihs/leihs.git apps/leihs
git submodule add git@github.com:ooofinooo/listenup.git apps/listenup
git submodule add git@github.com:tootsuite/mastodon.git apps/mastodon
git submodule add git@github.com:mumuki/mumuki-laboratory.git apps/mumuki-laboratory
git submodule add git@github.com:sunlightlabs/opencongress.git apps/opencongress
git submodule add git@github.com:openfarmcc/OpenFarm.git apps/OpenFarm
git submodule add git@github.com:ossfriday/ossfriday.git apps/ossfriday
git submodule add git@github.com:otwcode/otwarchive.git apps/otwarchive
git submodule add git@github.com:pglombardo/PasswordPusher.git apps/PasswordPusher
git submodule add git@github.com:netguru/people.git apps/people
git submodule add git@github.com:openaustralia/planningalerts.git apps/planningalerts
git submodule add git@github.com:pophealth/popHealth.git apps/popHealth
git submodule add git@github.com:jdjkelly/quant.git apps/quant
git submodule add git@github.com:scottwillson/racing_on_rails.git apps/racing_on_rails
git submodule add git@github.com:rapidftr/RapidFTR.git apps/RapidFTR
git submodule add git@github.com:balanced/rentmybikes-rails.git apps/rentmybikes-rails
git submodule add git@github.com:rletters/rletters.git apps/rletters
git submodule add git@github.com:mertbulan/RoRdit.git apps/RoRdit
git submodule add git@github.com:rubygems/rubygems.org.git apps/rubygems.org
git submodule add git@github.com:kaznum/sanataro.git apps/sanataro
git submodule add git@github.com:psu-stewardship/scholarsphere.git apps/scholarsphere
git submodule add git@github.com:lockitron/selfstarter.git apps/selfstarter
git submodule add git@github.com:scaffeinate/socify.git apps/socify
git submodule add git@github.com:Spokenvote/spokenvote.git apps/spokenvote
git submodule add git@github.com:spree/spree.git apps/spree
git submodule add git@github.com:liaoziyang/stackneveroverflow.git apps/stackneveroverflow
git submodule add git@github.com:teambox/teambox.git apps/teambox
git submodule add git@github.com:TheOdinProject/theodinproject.git apps/theodinproject
git submodule add git@github.com:Jellyfishboy/trado.git apps/trado
git submodule add git@github.com:AgileVentures/WebsiteOne.git apps/WebsiteOne