#!/bin/bash
git submodule add git@github.com:bundler/bundler.git apps/bundler
git submodule add git@github.com:rspec/rspec-core.git apps/rspec-core
git submodule add git@github.com:halostatue/diff-lcs.git apps/diff-lcs
git submodule add git@github.com:rspec/rspec-expectations.git apps/rspec-expectations
git submodule add git@github.com:rspec/rspec-mocks.git apps/rspec-mocks
git submodule add git@github.com:intridea/multi_json.git apps/multi_json
git submodule add git@github.com:rspec/rspec.git apps/rspec
git submodule add git@github.com:ruby/rake.git apps/rake
git submodule add git@github.com:rack/rack.git apps/rack
git submodule add git@github.com:rspec/rspec-support.git apps/rspec-support
git submodule add git@github.com:mime-types/ruby-mime-types.git apps/ruby-mime-types
git submodule add git@github.com:svenfuchs/i18n.git apps/i18n
git submodule add git@github.com:erikhuda/thor.git apps/thor
git submodule add git@github.com:tzinfo/tzinfo.git apps/tzinfo
git submodule add git@github.com:sparklemotion/nokogiri.git apps/nokogiri
git submodule add git@github.com:jimweirich/builder.git apps/builder
git submodule add git@github.com:seattlerb/minitest.git apps/minitest
git submodule add git@github.com:ruby-concurrency/thread_safe.git apps/thread_safe
git submodule add git@github.com:sass/sass.git apps/sass
git submodule add git@github.com:kwatch/erubis.git apps/erubis
git submodule add git@github.com:rack-test/rack-test.git apps/rack-test
git submodule add git@github.com:mikel/mail.git apps/mail
git submodule add git@github.com:ffi/ffi.git apps/ffi
git submodule add git@github.com:sporkmonger/addressable.git apps/addressable
git submodule add git@github.com:lostisland/faraday.git apps/faraday
git submodule add git@github.com:lautis/uglifier.git apps/uglifier
git submodule add git@github.com:nicksieger/multipart-post.git apps/multipart-post
git submodule add git@github.com:thuehlinger/daemons.git apps/daemons
git submodule add git@github.com:rest-client/rest-client.git apps/rest-client
git submodule add git@github.com:banister/method_source.git apps/method_source
git submodule add git@github.com:net-ssh/net-ssh.git apps/net-ssh
git submodule add git@github.com:rubychan/coderay.git apps/coderay
git submodule add git@github.com:aws/aws-sdk-ruby.git apps/aws-sdk-ruby
git submodule add git@github.com:pry/pry.git apps/pry
git submodule add git@github.com:flavorjones/loofah.git apps/loofah
git submodule add git@github.com:flavorjones/mini_portile.git apps/mini_portile
git submodule add git@github.com:rails/globalid.git apps/globalid
git submodule add git@github.com:sstephenson/hike.git apps/hike
git submodule add git@github.com:eventmachine/eventmachine.git apps/eventmachine
git submodule add git@github.com:leejarvis/slop.git apps/slop
git submodule add git@github.com:rubyzip/rubyzip.git apps/rubyzip
git submodule add git@github.com:redis/redis-rb.git apps/redis-rb
git submodule add git@github.com:ruby-concurrency/concurrent-ruby.git apps/concurrent-ruby
git submodule add git@github.com:heroku/netrc.git apps/netrc
git submodule add git@github.com:ruby/rdoc.git apps/rdoc
git submodule add git@github.com:rails/jbuilder.git apps/jbuilder
git submodule add git@github.com:flavorjones/mini_portile.git apps/mini_portile
git submodule add git@github.com:excon/excon.git apps/excon
git submodule add git@github.com:jmespath/jmespath.rb.git apps/jmespath.rb
git submodule add git@github.com:sferik/multi_xml.git apps/multi_xml
git submodule add git@github.com:thibaudgg/rb-fsevent.git apps/rb-fsevent
git submodule add git@github.com:intridea/hashie.git apps/hashie
git submodule add git@github.com:cjheath/treetop.git apps/treetop
git submodule add git@github.com:ged/ruby-pg.git apps/ruby-pg
git submodule add git@github.com:knu/ruby-unf.git apps/ruby-unf
git submodule add git@github.com:guard/rb-inotify.git apps/rb-inotify
git submodule add git@github.com:JEG2/highline.git apps/highline
git submodule add git@github.com:knu/ruby-domain_name.git apps/ruby-domain_name
git submodule add git@github.com:net-ssh/net-scp.git apps/net-scp
git submodule add git@github.com:awesome-print/awesome_print.git apps/awesome_print
git submodule add git@github.com:sparklemotion/sqlite3-ruby.git apps/sqlite3-ruby
git submodule add git@github.com:sparklemotion/http-cookie.git apps/http-cookie
git submodule add git@github.com:brianmario/mysql2.git apps/mysql2
git submodule add git@github.com:jnunemaker/httparty.git apps/httparty
git submodule add git@github.com:zzak/sdoc.git apps/sdoc
git submodule add git@github.com:jwt/ruby-jwt.git apps/ruby-jwt
git submodule add git@github.com:rspec/rspec-rails.git apps/rspec-rails
git submodule add git@github.com:macournoyer/thin.git apps/thin
git submodule add git@github.com:geemus/formatador.git apps/formatador
git submodule add git@github.com:colszowka/simplecov.git apps/simplecov
git submodule add git@github.com:colszowka/simplecov-html.git apps/simplecov-html
git submodule add git@github.com:teamcapybara/capybara.git apps/capybara
git submodule add git@github.com:lostisland/faraday_middleware.git apps/faraday_middleware
git submodule add git@github.com:enkessler/childprocess.git apps/childprocess
git submodule add git@github.com:deivid-rodriguez/byebug.git apps/byebug
git submodule add git@github.com:jfelchner/ruby-progressbar.git apps/ruby-progressbar
git submodule add git@github.com:ms-ati/docile.git apps/docile
git submodule add git@github.com:weppos/publicsuffix-ruby.git apps/publicsuffix-ruby
git submodule add git@github.com:newrelic/rpm.git apps/rpm
git submodule add git@github.com:haml/haml.git apps/haml
git submodule add git@github.com:sickill/rainbow.git apps/rainbow
git submodule add git@github.com:teamcapybara/xpath.git apps/xpath
git submodule add git@github.com:codahale/bcrypt-ruby.git apps/bcrypt-ruby
git submodule add git@github.com:thoughtbot/factory_bot.git apps/factory_bot
git submodule add git@github.com:wardencommunity/warden.git apps/warden
git submodule add git@github.com:maik/xml-simple.git apps/xml-simple
git submodule add git@github.com:plataformatec/devise.git apps/devise
git submodule add git@github.com:dtao/safe_yaml.git apps/safe_yaml
git submodule add git@github.com:guard/listen.git apps/listen
git submodule add git@github.com:whitequark/parser.git apps/parser
git submodule add git@github.com:ianwhite/orm_adapter.git apps/orm_adapter
git submodule add git@github.com:jnunemaker/crack.git apps/crack
git submodule add git@github.com:nahi/httpclient.git apps/httpclient
git submodule add git@github.com:wvanbergen/chunky_png.git apps/chunky_png
git submodule add git@github.com:bbatsov/rubocop.git apps/rubocop
git submodule add git@github.com:bblimke/webmock.git apps/webmock
git submodule add git@github.com:DatabaseCleaner/database_cleaner.git apps/database_cleaner
git submodule add git@github.com:puma/puma.git apps/puma
git submodule add git@github.com:bkeepers/dotenv.git apps/dotenv
git submodule add git@github.com:ipaddress-gem/ipaddress.git apps/ipaddress
git submodule add git@github.com:plataformatec/responders.git apps/responders
git submodule add git@github.com:janlelis/unicode-display_width.git apps/unicode-display_width
git submodule add git@github.com:faye/websocket-driver-ruby.git apps/websocket-driver-ruby
git submodule add git@github.com:mperham/connection_pool.git apps/connection_pool
git submodule add git@github.com:rtomayko/rack-cache.git apps/rack-cache
git submodule add git@github.com:cowboyd/libv8.git apps/libv8
git submodule add git@github.com:resque/redis-namespace.git apps/redis-namespace
git submodule add git@github.com:kaminari/kaminari.git apps/kaminari
git submodule add git@github.com:sporkmonger/uuidtools.git apps/uuidtools
git submodule add git@github.com:bbatsov/powerpack.git apps/powerpack
git submodule add git@github.com:travisjeffery/timecop.git apps/timecop
git submodule add git@github.com:fog/fog-core.git apps/fog-core
git submodule add git@github.com:faye/websocket-extensions-ruby.git apps/websocket-extensions-ruby
git submodule add git@github.com:oauth-xx/oauth2.git apps/oauth2
git submodule add git@github.com:grosser/parallel.git apps/parallel
git submodule add git@github.com:fog/fog.git apps/fog
git submodule add git@github.com:rails/spring.git apps/spring
git submodule add git@github.com:cowboyd/therubyracer.git apps/therubyracer
git submodule add git@github.com:socketry/timers.git apps/timers
git submodule add git@github.com:banister/debug_inspector.git apps/debug_inspector
git submodule add git@github.com:celluloid/celluloid.git apps/celluloid
git submodule add git@github.com:fog/fog-json.git apps/fog-json
git submodule add git@github.com:mperham/sidekiq.git apps/sidekiq
git submodule add git@github.com:stympy/faker.git apps/faker
git submodule add git@github.com:ahoward/systemu.git apps/systemu
git submodule add git@github.com:tj/terminal-table.git apps/terminal-table
git submodule add git@github.com:banister/binding_of_caller.git apps/binding_of_caller
git submodule add git@github.com:twbs/bootstrap-sass.git apps/bootstrap-sass
git submodule add git@github.com:threedaymonk/htmlentities.git apps/htmlentities
git submodule add git@github.com:socketry/nio4r.git apps/nio4r
git submodule add git@github.com:tmm1/http_parser.rb.git apps/http_parser.rb
git submodule add git@github.com:ddollar/foreman.git apps/foreman
git submodule add git@github.com:imanel/websocket-ruby.git apps/websocket-ruby
git submodule add git@github.com:capistrano/capistrano.git apps/capistrano
git submodule add git@github.com:mojombo/chronic.git apps/chronic
git submodule add git@github.com:ruby-concurrency/ref.git apps/ref
git submodule add git@github.com:steveklabnik/request_store.git apps/request_store
git submodule add git@github.com:fog/fog-aws.git apps/fog-aws
git submodule add git@github.com:TwP/logging.git apps/logging
git submodule add git@github.com:brianmario/yajl-ruby.git apps/yajl-ruby
git submodule add git@github.com:jmettraux/rufus-scheduler.git apps/rufus-scheduler
git submodule add git@github.com:fazibear/colorize.git apps/colorize
git submodule add git@github.com:fog/fog-xml.git apps/fog-xml
git submodule add git@github.com:thoughtbot/shoulda-matchers.git apps/shoulda-matchers
git submodule add git@github.com:ManageIQ/trollop.git apps/trollop
git submodule add git@github.com:ai/autoprefixer-rails.git apps/autoprefixer-rails
git submodule add git@github.com:omniauth/omniauth.git apps/omniauth
git submodule add git@github.com:dkubb/equalizer.git apps/equalizer