# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LabelsController, type: :controller do
  before do
    sign_in user
  end

  let(:valid_attributes) do
    {
      application_name: "Custom Name",
      institution_name: "Custom Inst Name",
      institution_name_full: "Custom Full Inst Name"
    }
  end

  let(:invalid_attributes) do
    { application_name: "" }
  end

  context 'with an unprivileged user' do
    let(:user) { FactoryGirl.create(:user) }

    describe "GET #edit" do
      it "denies the request" 

    end

    describe "PUT #update" do
      it "denies the request" 

    end
  end

  context 'with an administrator' do
    let(:user) { FactoryGirl.create(:admin) }

    describe "GET #edit" do
      it "assigns the requested site as @site" 

    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) do
          {
            application_name: "New Custom Name",
            institution_name: "New Custom Inst Name",
            institution_name_full: "New Full Custom Inst Name"
          }
        end

        it "updates the requested site" 


        it "assigns the requested site as @site" 


        it "redirects to the site" 

      end

      context "with invalid params" do
        it "assigns the site as @site" 


        it "re-renders the 'edit' template" 

      end
    end
  end
end

